-- ============================================================
-- LOAN APPLICATION MODULE
-- ideal_pay database
-- ------------------------------------------------------------
-- Tables:
--   1. loan              (ALTER — add eligibility fields)
--   2. loan_application  (new — application lifecycle)
--   3. loan_installment  (new — repayment schedule)
-- ============================================================

-- ============================================================
-- 1. Enhance loan master table
--    Add eligibility and limit fields
-- ============================================================
ALTER TABLE `loan`
  ADD COLUMN `max_amount`       decimal(15,2) NOT NULL DEFAULT '0.00'
      COMMENT 'Maximum amount an employee can apply for'
      AFTER `amount`,
  ADD COLUMN `max_installments` int           NOT NULL DEFAULT 0
      COMMENT 'Maximum repayment period in months'
      AFTER `max_amount`,
  ADD COLUMN `min_service_months` int         NOT NULL DEFAULT 0
      COMMENT 'Minimum months of service required to be eligible'
      AFTER `max_installments`;

-- Update the default row to reflect the new columns cleanly
UPDATE `loan`
SET max_amount = 0.00, max_installments = 0, min_service_months = 0
WHERE id = -1;

-- ============================================================
-- 2. loan_application
--    One row per application — tracks the full lifecycle from
--    PENDING through APPROVED/REJECTED to ACTIVE and CLOSED.
-- ============================================================
DROP TABLE IF EXISTS `loan_application`;

CREATE TABLE `loan_application` (
  `id`                 bigint        NOT NULL AUTO_INCREMENT,

  -- Reference number generated by application (LNA-YYYY-NNNNN)
  `loan_no`            varchar(25)   NOT NULL,

  -- Core relationships
  `emp_id`             bigint        NOT NULL,
  `loan_type_id`       bigint        NOT NULL   COMMENT 'FK → loan.id',

  -- Application details
  `applied_date`       date          NOT NULL,
  `principal_amount`   decimal(15,2) NOT NULL DEFAULT '0.00',
  `installments`       int           NOT NULL DEFAULT 1
                           COMMENT 'Total number of monthly installments',
  `monthly_installment` decimal(15,2) NOT NULL DEFAULT '0.00'
                           COMMENT 'Calculated: principal_amount / installments',
  `start_payroll_month` varchar(20)  NOT NULL
                           COMMENT 'First deduction month e.g. 2026-07',
  `remarks`            varchar(500)  DEFAULT NULL,

  -- Status workflow:
  --   PENDING → APPROVED or REJECTED
  --   APPROVED → ACTIVE (when first installment processed)
  --   ACTIVE   → CLOSED (when all installments paid / manually closed)
  `status`             varchar(20)   NOT NULL DEFAULT 'PENDING'
                           COMMENT 'PENDING | APPROVED | REJECTED | ACTIVE | CLOSED',

  -- Approval / rejection
  `approved_by`        bigint        DEFAULT NULL,
  `approved_date`      datetime      DEFAULT NULL,
  `rejected_by`        bigint        DEFAULT NULL,
  `rejected_date`      datetime      DEFAULT NULL,
  `rejection_reason`   varchar(500)  DEFAULT NULL,

  -- Disbursement
  `disbursed_amount`   decimal(15,2) NOT NULL DEFAULT '0.00',
  `disbursed_date`     date          DEFAULT NULL,

  -- Running totals (updated as installments are paid)
  `paid_installments`  int           NOT NULL DEFAULT 0,
  `outstanding_balance` decimal(15,2) NOT NULL DEFAULT '0.00'
                           COMMENT 'Remaining principal still to be deducted',
  `closed_date`        date          DEFAULT NULL,

  -- Soft delete / active flag
  `is_active`          char(1)       NOT NULL DEFAULT 'Y',

  -- Audit
  `created_by`         bigint        NOT NULL,
  `created_date`       timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by`        bigint        NOT NULL,
  `modified_date`      timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP
                           ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  UNIQUE  KEY `uk_loan_application_no`      (`loan_no`),
  KEY `fk_la_emp_id`                        (`emp_id`),
  KEY `fk_la_loan_type_id`                  (`loan_type_id`),
  KEY `fk_la_approved_by`                   (`approved_by`),
  KEY `fk_la_rejected_by`                   (`rejected_by`),
  KEY `fk_la_created_by`                    (`created_by`),
  KEY `fk_la_modified_by`                   (`modified_by`),
  KEY `idx_la_emp_status`                   (`emp_id`, `status`),
  KEY `idx_la_status`                       (`status`),

  CONSTRAINT `fk_la_emp_id`
      FOREIGN KEY (`emp_id`)        REFERENCES `employee` (`id`),
  CONSTRAINT `fk_la_loan_type_id`
      FOREIGN KEY (`loan_type_id`)  REFERENCES `loan` (`id`),
  CONSTRAINT `fk_la_approved_by`
      FOREIGN KEY (`approved_by`)   REFERENCES `usr` (`id`),
  CONSTRAINT `fk_la_rejected_by`
      FOREIGN KEY (`rejected_by`)   REFERENCES `usr` (`id`),
  CONSTRAINT `fk_la_created_by`
      FOREIGN KEY (`created_by`)    REFERENCES `usr` (`id`),
  CONSTRAINT `fk_la_modified_by`
      FOREIGN KEY (`modified_by`)   REFERENCES `usr` (`id`),

  CONSTRAINT `chk_la_status`
      CHECK (`status` IN ('PENDING','APPROVED','REJECTED','ACTIVE','CLOSED')),
  CONSTRAINT `chk_la_active`
      CHECK (`is_active` IN ('Y','N')),
  CONSTRAINT `chk_la_installments`
      CHECK (`installments` >= 1),
  CONSTRAINT `chk_la_principal`
      CHECK (`principal_amount` > 0)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Loan application lifecycle — one row per employee loan request';

-- System default row
INSERT INTO `loan_application`
  (id, loan_no, emp_id, loan_type_id, applied_date, principal_amount,
   installments, monthly_installment, start_payroll_month, status,
   disbursed_amount, paid_installments, outstanding_balance, is_active,
   created_by, created_date, modified_by, modified_date)
VALUES
  (-1, 'LNA-DEFAULT', -1, -1, '2026-01-01', 0.00,
   1, 0.00, 'MMYYYY', 'PENDING',
   0.00, 0, 0.00, 'N',
   -1, '2026-05-17 12:34:46', -1, '2026-05-17 12:34:46');

-- Sample approved applications
INSERT INTO `loan_application`
  (loan_no, emp_id, loan_type_id, applied_date, principal_amount,
   installments, monthly_installment, start_payroll_month, status,
   approved_by, approved_date, disbursed_amount, disbursed_date,
   paid_installments, outstanding_balance, remarks, is_active,
   created_by, modified_by)
VALUES
  ('LNA-2026-00001', 1, -1, '2026-01-05', 120000.00,
   24, 5000.00, '2026-02', 'ACTIVE',
   1, '2026-01-10 09:00:00', 120000.00, '2026-01-10',
   5, 95000.00, 'Vehicle loan - Toyota', 'Y', 1, 1),

  ('LNA-2026-00002', 2, -1, '2026-01-08', 60000.00,
   12, 5000.00, '2026-02', 'ACTIVE',
   1, '2026-01-12 10:00:00', 60000.00, '2026-01-12',
   5, 35000.00, 'Personal emergency', 'Y', 1, 1),

  ('LNA-2026-00003', 3, -1, '2026-02-01', 240000.00,
   36, 6666.67, '2026-03', 'ACTIVE',
   1, '2026-02-05 09:30:00', 240000.00, '2026-02-05',
   3, 220000.07, 'Housing renovation', 'Y', 1, 1),

  ('LNA-2026-00004', 4, -1, '2026-02-14', 90000.00,
   18, 5000.00, '2026-03', 'PENDING',
   NULL, NULL, 0.00, NULL,
   0, 90000.00, 'Education fees', 'Y', 1, 1),

  ('LNA-2026-00005', 5, -1, '2026-02-20', 150000.00,
   30, 5000.00, '2026-03', 'REJECTED',
   1, '2026-02-25 11:00:00', 0.00, NULL,
   0, 150000.00, 'Exceeded eligibility limit', 'Y', 1, 1),

  ('LNA-2026-00006', 6, -1, '2026-03-01', 48000.00,
   12, 4000.00, '2026-04', 'APPROVED',
   1, '2026-03-05 10:00:00', 48000.00, '2026-03-05',
   0, 48000.00, 'Medical expenses', 'Y', 1, 1);

-- ============================================================
-- 3. loan_installment
--    One row per scheduled monthly repayment.
--    Generated automatically when application is APPROVED.
--    Links back to emp_loan when the payroll deduction is made.
-- ============================================================
DROP TABLE IF EXISTS `loan_installment`;

CREATE TABLE `loan_installment` (
  `id`                bigint        NOT NULL AUTO_INCREMENT,
  `application_id`    bigint        NOT NULL   COMMENT 'FK → loan_application.id',
  `installment_no`    int           NOT NULL   COMMENT 'Sequence 1..N',
  `payroll_month`     varchar(20)   NOT NULL   COMMENT 'e.g. 2026-07',

  -- Amounts
  `scheduled_amount`  decimal(15,2) NOT NULL DEFAULT '0.00'
                          COMMENT 'Amount due this installment',
  `paid_amount`       decimal(15,2) NOT NULL DEFAULT '0.00'
                          COMMENT 'Actual amount deducted',

  -- Status:
  --   PENDING  → due but not yet processed
  --   PAID     → fully deducted via payroll
  --   PARTIAL  → partially deducted (manual adjustment)
  --   SKIPPED  → waived or deferred for this month
  `status`            varchar(10)   NOT NULL DEFAULT 'PENDING'
                          COMMENT 'PENDING | PAID | PARTIAL | SKIPPED',

  `paid_date`         date          DEFAULT NULL,

  -- Link to the actual payroll deduction record
  `emp_loan_id`       bigint        DEFAULT NULL
                          COMMENT 'FK → emp_loan.id when deducted in payroll',
  `notes`             varchar(255)  DEFAULT NULL,

  -- Audit
  `created_by`        bigint        NOT NULL,
  `created_date`      timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_by`       bigint        NOT NULL,
  `modified_date`     timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP
                          ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  UNIQUE  KEY `uk_loan_installment`     (`application_id`, `installment_no`),
  KEY `fk_li_application_id`           (`application_id`),
  KEY `fk_li_emp_loan_id`              (`emp_loan_id`),
  KEY `fk_li_created_by`               (`created_by`),
  KEY `fk_li_modified_by`              (`modified_by`),
  KEY `idx_li_payroll_month`           (`payroll_month`),
  KEY `idx_li_status`                  (`status`),

  CONSTRAINT `fk_li_application_id`
      FOREIGN KEY (`application_id`) REFERENCES `loan_application` (`id`)
      ON DELETE CASCADE,
  CONSTRAINT `fk_li_emp_loan_id`
      FOREIGN KEY (`emp_loan_id`)    REFERENCES `emp_loan` (`id`)
      ON DELETE SET NULL,
  CONSTRAINT `fk_li_created_by`
      FOREIGN KEY (`created_by`)     REFERENCES `usr` (`id`),
  CONSTRAINT `fk_li_modified_by`
      FOREIGN KEY (`modified_by`)    REFERENCES `usr` (`id`),

  CONSTRAINT `chk_li_status`
      CHECK (`status` IN ('PENDING','PAID','PARTIAL','SKIPPED')),
  CONSTRAINT `chk_li_installment_no`
      CHECK (`installment_no` >= 1)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Repayment schedule — one row per monthly installment per application';

-- System default row
INSERT INTO `loan_installment`
  (id, application_id, installment_no, payroll_month,
   scheduled_amount, paid_amount, status,
   created_by, modified_by)
VALUES
  (-1, -1, 0, 'MMYYYY', 0.00, 0.00, 'PENDING', -1, -1);

-- Sample installment schedule for LNA-2026-00001 (app id 1, 24 installments)
-- First 5 are PAID, remaining are PENDING
INSERT INTO `loan_installment`
  (application_id, installment_no, payroll_month,
   scheduled_amount, paid_amount, status, paid_date, created_by, modified_by)
VALUES
  (1,  1, '2026-02', 5000.00, 5000.00, 'PAID',    '2026-02-28', 1, 1),
  (1,  2, '2026-03', 5000.00, 5000.00, 'PAID',    '2026-03-31', 1, 1),
  (1,  3, '2026-04', 5000.00, 5000.00, 'PAID',    '2026-04-30', 1, 1),
  (1,  4, '2026-05', 5000.00, 5000.00, 'PAID',    '2026-05-31', 1, 1),
  (1,  5, '2026-06', 5000.00, 5000.00, 'PAID',    '2026-06-30', 1, 1),
  (1,  6, '2026-07', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1,  7, '2026-08', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1,  8, '2026-09', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1,  9, '2026-10', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 10, '2026-11', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 11, '2026-12', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 12, '2027-01', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 13, '2027-02', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 14, '2027-03', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 15, '2027-04', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 16, '2027-05', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 17, '2027-06', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 18, '2027-07', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 19, '2027-08', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 20, '2027-09', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 21, '2027-10', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 22, '2027-11', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 23, '2027-12', 5000.00, 0.00,    'PENDING',  NULL,         1, 1),
  (1, 24, '2028-01', 5000.00, 0.00,    'PENDING',  NULL,         1, 1);

-- Sample schedule for LNA-2026-00002 (app id 2, 12 installments)
INSERT INTO `loan_installment`
  (application_id, installment_no, payroll_month,
   scheduled_amount, paid_amount, status, paid_date, created_by, modified_by)
VALUES
  (2,  1, '2026-02', 5000.00, 5000.00, 'PAID',   '2026-02-28', 1, 1),
  (2,  2, '2026-03', 5000.00, 5000.00, 'PAID',   '2026-03-31', 1, 1),
  (2,  3, '2026-04', 5000.00, 5000.00, 'PAID',   '2026-04-30', 1, 1),
  (2,  4, '2026-05', 5000.00, 5000.00, 'PAID',   '2026-05-31', 1, 1),
  (2,  5, '2026-06', 5000.00, 5000.00, 'PAID',   '2026-06-30', 1, 1),
  (2,  6, '2026-07', 5000.00, 0.00,    'PENDING', NULL,         1, 1),
  (2,  7, '2026-08', 5000.00, 0.00,    'PENDING', NULL,         1, 1),
  (2,  8, '2026-09', 5000.00, 0.00,    'PENDING', NULL,         1, 1),
  (2,  9, '2026-10', 5000.00, 0.00,    'PENDING', NULL,         1, 1),
  (2, 10, '2026-11', 5000.00, 0.00,    'PENDING', NULL,         1, 1),
  (2, 11, '2026-12', 5000.00, 0.00,    'PENDING', NULL,         1, 1),
  (2, 12, '2027-01', 5000.00, 0.00,    'PENDING', NULL,         1, 1);

-- ============================================================
-- Stored Procedures
-- ============================================================

-- ── sp_generate_loan_no ───────────────────────────────────────────────────
-- Generates next sequential loan reference number: LNA-YYYY-NNNNN
DROP PROCEDURE IF EXISTS `sp_generate_loan_no`;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_generate_loan_no`(
    IN  p_year  INT,
    OUT p_loan_no VARCHAR(25)
)
BEGIN
    DECLARE v_next_seq INT DEFAULT 1;

    SELECT IFNULL(MAX(
        CAST(SUBSTRING_INDEX(loan_no, '-', -1) AS UNSIGNED)
    ), 0) + 1
    INTO v_next_seq
    FROM loan_application
    WHERE loan_no LIKE CONCAT('LNA-', p_year, '-%')
      AND id > 0;

    SET p_loan_no = CONCAT('LNA-', p_year, '-', LPAD(v_next_seq, 5, '0'));
END ;;
DELIMITER ;

-- ── sp_create_loan_schedule ───────────────────────────────────────────────
-- Generates loan_installment rows for an APPROVED application.
-- Call after updating status to APPROVED.
DROP PROCEDURE IF EXISTS `sp_create_loan_schedule`;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_create_loan_schedule`(
    IN p_application_id BIGINT,
    IN p_created_by     BIGINT
)
BEGIN
    DECLARE v_installments       INT;
    DECLARE v_monthly_installment DECIMAL(15,2);
    DECLARE v_start_month        VARCHAR(20);
    DECLARE v_cur_year           INT;
    DECLARE v_cur_month          INT;
    DECLARE v_i                  INT DEFAULT 1;
    DECLARE v_payroll_month      VARCHAR(20);

    -- Fetch application header
    SELECT installments, monthly_installment, start_payroll_month
    INTO   v_installments, v_monthly_installment, v_start_month
    FROM   loan_application
    WHERE  id = p_application_id;

    SET v_cur_year  = CAST(SUBSTRING_INDEX(v_start_month, '-', 1)  AS UNSIGNED);
    SET v_cur_month = CAST(SUBSTRING_INDEX(v_start_month, '-', -1) AS UNSIGNED);

    -- Remove any existing schedule (re-generate on re-approval)
    DELETE FROM loan_installment
    WHERE  application_id = p_application_id AND id > 0;

    -- Insert one row per installment
    WHILE v_i <= v_installments DO
        SET v_payroll_month = CONCAT(v_cur_year, '-', LPAD(v_cur_month, 2, '0'));

        INSERT INTO loan_installment
          (application_id, installment_no, payroll_month,
           scheduled_amount, paid_amount, status,
           created_by, modified_by)
        VALUES
          (p_application_id, v_i, v_payroll_month,
           v_monthly_installment, 0.00, 'PENDING',
           p_created_by, p_created_by);

        -- Advance month
        SET v_cur_month = v_cur_month + 1;
        IF v_cur_month > 12 THEN
            SET v_cur_month = 1;
            SET v_cur_year  = v_cur_year + 1;
        END IF;

        SET v_i = v_i + 1;
    END WHILE;

    -- Initialise outstanding balance
    UPDATE loan_application
    SET    outstanding_balance = principal_amount,
           paid_installments   = 0
    WHERE  id = p_application_id;
END ;;
DELIMITER ;

-- ── sp_loan_application_summary ───────────────────────────────────────────
-- Per-employee loan summary for a given status or ALL.
DROP PROCEDURE IF EXISTS `sp_loan_application_summary`;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_loan_application_summary`(
    IN p_status VARCHAR(20)    -- pass NULL for all statuses
)
BEGIN
    SELECT
        e.id                                   AS emp_id,
        e.employee_no,
        e.payroll_name,
        l.name                                 AS loan_type,
        la.loan_no,
        la.applied_date,
        la.principal_amount,
        la.installments,
        la.monthly_installment,
        la.paid_installments,
        la.outstanding_balance,
        la.status,
        la.start_payroll_month,
        la.disbursed_date,
        la.closed_date,
        la.remarks
    FROM  loan_application la
    JOIN  employee e ON la.emp_id      = e.id
    JOIN  loan     l ON la.loan_type_id = l.id
    WHERE la.id > 0
      AND (p_status IS NULL OR la.status = p_status)
    ORDER BY la.applied_date DESC, e.employee_no;
END ;;
DELIMITER ;

-- ── sp_employee_loan_statement ────────────────────────────────────────────
-- Full installment statement for one employee application.
DROP PROCEDURE IF EXISTS `sp_employee_loan_statement`;
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_employee_loan_statement`(
    IN p_application_id BIGINT
)
BEGIN
    SELECT
        la.loan_no,
        e.employee_no,
        e.payroll_name,
        l.name                  AS loan_type,
        la.principal_amount,
        la.installments,
        la.monthly_installment,
        la.outstanding_balance,
        la.status               AS application_status,
        li.installment_no,
        li.payroll_month,
        li.scheduled_amount,
        li.paid_amount,
        li.status               AS installment_status,
        li.paid_date
    FROM  loan_installment  li
    JOIN  loan_application  la ON li.application_id = la.id
    JOIN  employee          e  ON la.emp_id          = e.id
    JOIN  loan              l  ON la.loan_type_id    = l.id
    WHERE li.application_id = p_application_id
      AND li.id > 0
    ORDER BY li.installment_no;
END ;;
DELIMITER ;
